### ISSUE TITLE
STL model of Ultrasonix BPC8-4/10 & BPL9-5/55 Transrectal probe

### ISSUE THREAD

**Issue by ai-ray** [PlusToolkit/PlusModelCatalog#5]
Dear All, 
for a starting project, I need the 3D model of the BPC8-4/10 & BPL9-5/55 Transrectal probe. 

Since I think there are other groups using the same probe, is it possible to add this model to the repository?

Thanks in advance for your support

**Comment by ungi** [comment]
Hi. I haven't used those models in the past, and none of my past Ultrasonix contacts work there anymore. If you can get a copy of those models, I would be happy to add them to the repository.

**Comment by lassoan** [comment]
@ungi That's the biplane transrectal Ultrasonix probe. It has a very simple geometry, so it could be probably measured and modeled relatively easily, but it would probably still take a couple of hours.

@ai-ray Would you like to try to model it using AutoCAD Fusion 360 software? (it is free)
If it helps, we may acquire a 3D scan of it that may help in the modeling.

**Comment by ungi** [comment]
True. It wouldn't take much time to make a model in Fusion 360 after surface scanning. I am working on a tutorial that is very similar to this task. In this video I'm designing a clip that matches the probe surface, but the probe itself could be modeled similarly. The video is unfinished and there is no narration yet, but here is a preview: https://1drv.ms/v/s!AhiABcbe1DBygotebJEY-OcNV2cXPg

**Comment by mxochicale** [comment]
Hi @ungi , thanks for sharing the nice video. I wondering if that is a CT scan of the probe and what were the parameters to perform the scanning. Also, it would be nice to know if there are any precautions if one decides to scan a ultrasound probe with a CT scanner.

**Comment by ungi** [comment]
Yes, CT scan. I wasn't there when they scanned it, but I don't think there are any precautions. X-ray is harmless to the ultrasound transducer. The CT technician will probably have a good guess what parameters to use.
