### ISSUE TITLE
suggestions for probe holder

### ISSUE THREAD

**Issue by fcenni** [PlusToolkit/PlusModelCatalog#6]
Hi,
I am working on a project for making a probe holder for this probe (from Telemed company): HL9.0/60/128Z-2 transducer. I got some ideas from your previous work here http://perk-software.cs.queensu.ca/plus/doc/nightly/modelcatalog/
I have some questions: do you recommend a single part (so a bit flexible), or 2 parts with an hinge? Which material to use for printing and for the type of hinge/s? Any suggestions/feedback is welcome!
Thanks for your help,
Francesco

**Comment by ungi** [comment]
Hi, ask for the CAD model of the transducer from Telemed. I have asked twice for different transducers and they have sent me the outer shell models for free. Once you have the model, you may send it to me so I can show how I would design the clip. Or you can try yourself. The best designs for me are the ones designed as one piece that elastically snaps to the probe. We don't have the latest designs on the model catalog.

**Comment by u0078867** [comment]
Hi, I am Francesco's colleague who will design the probe holder (for the snap-fit markers-holder shaft we already have an idea using a cantilever). I had the feeling the single-piece solution is better. We have a couple of 3D FDM printers here available. What material would you suggest? Nylon fibers? How thick would you recommend the elastic probe "jacket"? The thinner the more flexible, but also the more fragile ...

Thanks and regards!

**Comment by ungi** [comment]
Hi, I have not experimented with different materials or settings. Some of our printers have PLA, and other ABS, both work. I use 0.8 mm shell thickness (2x nozzle diameter). And 15-20% infill. The clip itself is 3-4 mm thick, depending on how tight we want it. I usually just experiment with 0.1-0.2 mm offsets inside to make it more stable. I'm sharing this information as a reference point for you, but I'm sure these are not the optimal settings. But when a clip just works for me, I stop improving it for lack of time.

**Comment by u0078867** [comment]
Forgot to closer this, but we came up with a our own (working) design, we can share it if useful to the community.
