### ISSUE TITLE
Configuration of fCal3.1

### ISSUE THREAD

**Issue by Leong1230** [PlusToolkit/PlusModelCatalog#9]
Hi!
What's the configuration of phantom fCal 3.1, including the coordinates of points 1--12 and the triangular holes under the phantom coordinate? Could you please provide the phantom definition file of fCal3.1 just as 'PhantomDefinition_fCal_2.1_Wiring_2.0.xml' for fCal2.1? Or how can I obtain the 1--12 point coordinates of fCal3.1?

Thank you!

**Comment by lassoan** [comment]
The configuration file is available here: https://github.com/PlusToolkit/PlusLibData/blob/master/ConfigFiles/PlusDeviceSet_fCal_Ultrasonix_C5-2_NDIPolaris_fCal3.xml

**Comment by Leong1230** [comment]
That's it! Thank you!
